name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update package version from tag
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG="${TAG#v}"
          echo "TAG=$TAG" >> "$GITHUB_ENV"
          VERSION="$(python setup.py --version)"
          if [ "$TAG" != "$VERSION" ]; then
            echo "Updating version from $VERSION to $TAG"
            sed -i -E "s/version=\"[^\"]+\"/version=\"$TAG\"/" setup.py
          fi

      - name: Commit version bump
        run: |
          if git diff --quiet; then
            echo "Version already up to date"
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit -am "Bump version to $TAG"
            git push
          fi

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build package
        run: |
          python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
